---
#
# SPDX-License-Identifier: GPL-3.0-or-later

default:
  image: "archlinux:latest"

lint:
  stage: build
  before_script:
    - pacman --noconfirm -Syu --needed base-devel shellcheck
  script:
    - make lint

build_images:
  stage: build
  before_script:
    - pacman --noconfirm -Syu --needed base-devel edk2-ovmf libvirt qemu ruby-bundler vagrant
    - pacman -Ss systemd
    - vagrant plugin install vagrant-libvirt
    - mkdir -vp /etc/systemd/system/multi-user.target.wants/
    - ln -svf /usr/lib/systemd/system/libvirtd.service /etc/systemd/system/multi-user.target.wants/libvirtd.service
    - /sbin/init
  script:
    - vagrant up --provider=libvirt
  tags:
    - secure-kvm
